org.gradle.jvmargs = -Xmx2G
org.gradle.daemon = false

# Project
version = 0.0.2
group = com.github.mahmudindev.mcmod.superflatdimension
description = Add superflat world type as separate dimension.

mod_id = superflatdimension
mod_name = Superflat Dimension
mod_authors = mahmudindev
mod_license = ARR

# General
java_version = 25
minecraft_version = 26.1

neoforge_loom_version = 2.0.141
neoforge_neoform_version = 1

# Fabric
fabric_loom_version = 1.15.5
fabric_loader_version = 0.19.2
fabric_api_version = 0.145.1

# NeoForge
neoforge_version = 26.1.0.19-beta
neoforge_version_range = [26.1,)
neoforge_loader_version_range = [4,)

# Dependencies
dimensionfixer_version = 0.0.9
worldportal_version = 0.0.9
