modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-superflatdimension/issues"
license = "ARR"

[[mods]]
modId = "superflatdimension"
version = "${version}"
displayName = "Superflat Dimension"
authors = "mahmudindev"
description = '''
Add superflat as separate dimension.
'''
logoFile = "assets/superflatdimension/icon.png"

[[dependencies.superflatdimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superflatdimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superflatdimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.superflatdimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "superflatdimension.mixins.json"
